### PR TITLE
add @hashgraph/hedera-wallet-connect-contributors group to have some c…

### LINKED ISSUE #143: Repo rules do not follow agreed up open source guidelines
Our current governance guidelines require 1 approval from SL, 1 approval from Hgraph, and 1 approval from a wallet provider. This sure to update, and we have a process for that.

It is understood that this delineation is not completely possible though github rules, though we can add a requirement for 3+ reviewers, and autoassign the active contributor group to PR's.

For more information: https://github.com/hashgraph/hedera-wallet-connect/wiki/WalletConnect-for-Hedera:-Repository-Governance#pull-request-approvals

If there's a need to update governance, please communicate the updates needed, otherwise please set up the repo to be more favorable for community contribution.

### PR DESCRIPTION
**Pull request by hgraphql**
…ode owner priviliges as @hashgraph/developer-advocates

**Description**:
Currently a member of @hashgraph/release-engineering @hashgraph/release-engineering-managers @hashgraph/developer-advocates needs to approve any PRs that merge into main. This PR adds the contributor group to the CODEOWNERs file, allowing the group to continue to develop this library

**Related issue(s)**:

Partially Fixes #143

**Notes for reviewer**:
Please also update the required # of approvals to 3.

### CODE REVIEW

**Review by rbarkerSL — CHANGES_REQUESTED** [review]
This PR may require some changes on which team(s) will be added to codeowners.

@nathanklick @rbarkerSL

**Comment by hgraphql** [comment]
> This PR may require some changes on which team(s) will be added to codeowners.
> 
> @nathanklick @rbarkerSL

@rbarkerSL okay, thank you. can you provide more information and a timeline?

**Comment by hgraphql** [comment]
@rbarkerSL @nathanklick an alternative is to add me / my team to the code owners as the project maintainers

**Comment by hgraphql** [comment]
closing this issue because of https://github.com/hashgraph/hedera-wallet-connect/issues/173 and the respective merge

**Pull request closed without merging**
